### ISSUE TITLE
Why is there a delay before executing?

### ISSUE THREAD

**Issue by casret** [coveo/exponential-backoff#1]
In many (most?) use cases, I think it would make more sense to try to first execution immediately, and then do the delay after executing.

**Comment by samisayegh** [comment]
Hi @casret, when I wrote the package, my thinking was as follows:

One would execute a request normally the first time that would error/fail. In the catch, one would diagnose the error. If the code was one that could be recovered from by retrying (e.g. a 429 returned due to the server throttling requests), one would pass the request into the `backoff` function, which would apply a delay before the first attempt.

What do you think? It seems in your case you want to backoff regardless?

**Comment by moodysalem** [comment]
You don't want to have two separate blocks of code that do the same thing, I would add an option for executing immediately that defaults to true because this is my expectation as well

**Comment by casret** [comment]
Yeah, Moody has is right, you don't want to have to write the same code in
two places.  When I checked out a few of the other packages they all
execute immediately.

**Comment by samisayegh** [comment]
I added a delayFirstAttempt option in this PR https://github.com/coveo/exponential-backoff/pull/4. The default value is `true` for now to stay inline with the existing behavior. I will change the default to `false` prior to releasing v2.x.x.

**Comment by samisayegh** [comment]
I released[ v1.2.0 on npm](https://www.npmjs.com/package/exponential-backoff/v/1.2.0) today that provides the `delayFirstAttempt` option. Will close those issue. Thanks for the feedback :)
