### ISSUE TITLE
Add jitter option

### ISSUE THREAD

**Issue by moodysalem** [coveo/exponential-backoff#2]
Add a `jitter` option-where this is used to prevent overloading servers with retries from many clients, a jitter is useful

https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/

**Comment by samisayegh** [comment]
Hey, I like the idea, thanks for the suggestion. Full jitter should be easy to implement, but I am having trouble understanding what the article terms "decorrelated jitter".

If we ignore setting maximum delay, then:
```
sleep = random_between(base, sleep * 3)
```

where
`base` is `startingDelay * 2 ** attempt` (i.e. the usual exponential backoff delay)
`sleep * 3` is the previous iteration delay multiplied by 3.

Does that sound right?

Looking at the graphs, decorrelated as compared to full jitter has a faster completion time (~6% faster), but uses more calls (~33% more). My intuition is during backoff mode, the priority should be on reducing the number of calls rather than having the fastest completion time (i.e. favoring the server over the client). I'm leaning towards implementing full jitter which seems simpler and more effective, but I am open to feedback.

**Comment by moodysalem** [comment]
I would type the `jitter` option something like `'none' | 'decorrelated' | 'full' | ((error: Error, attemptNumber: number, lastJitter: number) => jitterAmount)` and just implement both, with the default being `'none'`

**Comment by samisayegh** [comment]
I released[ v1.2.0 on npm](https://www.npmjs.com/package/exponential-backoff/v/1.2.0) today that provides the `jitter` option. For now, the possible values are `none` and `full`, with the possibility to add more in the future. Thanks for your feedback :)
